ssh_key: ENC[AES256_GCM,data:2CeC/myS8uUmh9RXMKvKFMOYIksZVdZ3r4ALLshoHbpx7EeBdNdyY0JrBe+MIjih/BbGZtRh12ynTSkmDtUyQ7tKmCFbmBkggCM1/iDkHvsQVn6/yv0b6KxUHfsXhyGvN9SZP2QXnq6AO0OX/YIV3kdl1oJGrbGiziFh8qVcva96t/FpyGndaDTJJMFK/BLMm6GRzrvzxWmtK9bmXplHLsp8EcVqa7M8JEkMOoRGjJOQHwXvQqnOUmdnn6M9RZYGsqvogJWO8YOms+Oi8/UUinpjce8pA5VEQvuX5A49Racm5OsbCf3VO9J/zUgTAOtz3e4PHpGGiPSbtkHkuZbI4YWux+USs6yYOLN2P1wtg+tepp5CNMhKgLmXBSW+agpNl+fdYuubiy0XeLIeIAXFIPINbLLA0LhEbJiCbfpNBu0OnBXcMM/psIY5AVdPrmr7NrmdLK024WTneBFLK7XQl/ZQ6xFhTBDcWA+pza0zd/fgBSdDc324WAzZOw9SK2RI4J6n1ZHVIdiY68J2R72JX35wao12HzMvkGBHYw+swrpH57o=,iv:w/Zo32E0Z6+HkbSNpl0F0iOUM3q0Cn/F0XdOHTJ4iwc=,tag:HEt8kFp7XXlOuyB9za7TCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTDI0WTQwV2N6UldjRHVB
            bDdDMFV0elVHeU9DSUpCSHlBVGxqL0oybWtjCjJiSWJGTFVQMDFpeEhDRHpKN2Vu
            NnE4RFpHc1p2bzI1NHpCenlpSDlGNjQKLS0tIGw3SEdpVld1eVQwU2J3SkFnV2hC
            VEc4dG5jNVBnMDJFbmdmci80OWJZRDAKhvEGparEWb5kNjQ4g8Tb1o7AY+xafTay
            IuM5GlynDSvYL0F3eKfbwwGKB1Ph/hO0nWnv8goAbI1pqjodHitKOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13xfa77f49ne56z3yyqh9qc9upjmrjfva8kcvg3jfem2m99dhr9fs34gdrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZ0lUZTBIU0UvbDFGSXk5
            OHNBZlpzRkZtUk9HRWVVMWxidDUzaXFJd1UwCmNDM3JPL0NETkpFQmpSemZPYUpt
            RjZwK2o2VGNUT0NhSGFwank5NlltVEkKLS0tIHMxbmxqcm13NDI2NXFFVjFERXJt
            MFlOOFYwck5mams0R0VLM3hZQmF0SFkKLVDaIuigbcqWJTeVNtRujA/SXhhXkS7O
            jOV7w9JtE/Pe5qQNYmur7/ANrTri/LScCwlreLALm4MYRGwaDzXt/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-26T01:50:45Z"
    mac: ENC[AES256_GCM,data:lNZcmVSpLMquIqygq4MkE31Q+eHBbt9KzrfvtB8ytdPv3nlsMpwJxjoalxtj8w7cHIclJaNlpXKy5KVF3xwvq3SklVA1s5okYUzvfUd0hXyQkJB0ZUAsu2eXKsLnD2iiypl1kdzkEmwV+3eVBJRULBytnskO6wLoY2HF3Z2HBjs=,iv:BcphvTPR/senLhI48InKyw6NhDgkJapZVGEmVtvseuI=,tag:lyvm+nwgQ4CUP/lkkMRBdA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
