github:
  access-token: ENC[AES256_GCM,data:fl/oS9BlkEDdHdED+yVW9/B50vPq02DRbeJr9HaKo7T0iEyYGjNyXg==,iv:ctBQjjMvWf/DpxbWsj5P4+vPHIbgnj2H2kNx0djgHhc=,tag:E790p7G8wcj7DmZmZRc12g==,type:str]
nix: ENC[AES256_GCM,data:9BQWWys1jfiLhAnZsz7frwgSB988PzPcO2b0g3nk2/P5yyBcGQuRONR0uKzKXs2iNquF5ZG56QZgk0vh1cc9Cewl4Q==,iv:p6beydvlmuc8RhMBdJyKXiUfJZmLpC0FPAfTVTm/ZUg=,tag:v/xi4ARU/lIiuE9abIbrRg==,type:str]
slack:
  token: ENC[AES256_GCM,data:Daghmguclia9+iIkiy3so7mGxiYGh1s4sQpScWmgx2qOp+99ECLXu1wV42yJyoCBSqIqYPpYoJCL006LLRGcmnarPknkJ+5s5IqLag==,iv:FkJHhOj6tMMaXfFDHLgngf6BYpF8G8W06RNjtXQsIlA=,tag:kmSMXCzO4bJ31ESw/zjgnw==,type:str]
twitch:
  token: ENC[AES256_GCM,data:HkF4lhkmw7tgv8nC3Q3l/9IbotYUfT8X8mkSB+wULCjc3OB1,iv:89fBsvWES5HXnTRy73EBnSUKzV6lZ3xJletS3RkDxVo=,tag:MHVpiLvo/mGc5adkU6Y0DA==,type:str]
slack-term: ENC[AES256_GCM,data:TmwjkICedhybgHW3jake57smgaQYGWBhwaXLa4iRzBaDZWwfILN7MMw3+ZuVkP2tRKeOW04R0Tl+88BWMxA9IxM0WoMPPMf4cW5zcKujXF+CiROv4MvOYjazwwX9/bVENQav3g==,iv:WipfYYRub4aGQk+gx7v3+JEbXSF9fboPBaMGgBKlcT8=,tag:DvIszr59crHC6HEtb32wQQ==,type:str]
tavily:
  access-token: ENC[AES256_GCM,data:lt9hS2k1jqv4Jme35g7r4HnuQ7ec83hd3ntibF2MnK/oVUcQ71lTjag=,iv:C08OgWZVjpOEAPWb7nXehxmUSs8lPDL4WERffBcHv1I=,tag:/ii11pOO9U/svb8rC1No2w==,type:str]
twitch-tui: ENC[AES256_GCM,data:GzNHfM0hsaV7Rj1A9PjNPcUOlwq+v5ESgJx00L7tuJrqI2IXsN+tYjRv/9MVzESDVZoRumD+rkixzjeKGSvTbn/NdxdzrdNLA2HzW+D5Ht/uM/O7XrEp8lxgWW3q5tkYIvAKomBQ6CtHq92azHgGuYSuQY3hust5Ga3BeXKgDFGbDQ==,iv:dhf4lhCpjfWQda/DmsfTvihDwL4ilUzSBj34tTMWgBw=,tag:zZ/uCDK0MbvEJDKxAQHs9w==,type:str]
wakatime: ENC[AES256_GCM,data:QPCDCRIXmul0Q4+WmA1btXdE6zdOwOqCbg5jEGtEk+6GkcVfUPAash5bMVgr2JX3x6mnyEziZDCmfPK6XzMMrx2G8O1+Grc6lgNDQrsgciSN5VBwQI1Xu2SswIbG3AqLdr5ZU0iN1Myyn9DtiOzlc2zDxpxPx19MHuYipx9FVl374/HTlZsbX2vPFrhLBCwtkGRWfA0ok3CTnayUNQ+bShQB1YRIir8lVk8+dlaFR5MEuWxeCCoI+3NWGlHLgig+hfPjocVyIXrDcqMveb358BEZN36TRsHAkUnd2g==,iv:/zLQEqD8rqlkYp2g6PW0m+bidkZfmnkzV6fmz/XkDsQ=,tag:iFCupamrTj7mwCkynE5gGw==,type:str]
weather_config: ENC[AES256_GCM,data:M0+aJ8H+iaSKhReDNuYSBZhUJG89He5+Ac8C9edcL/Ywl7qGN+P2jhUp55npZheOL6pSclWR1a6eZXhwRwV8s8qVmNs/nJbxdoVu97X5HcYOwBA0ieDOd10gDICIyktbZ22Zut8yDRSSKwXAGvq9EzZBNjOfWCDOWo3kTEbwwvqqMN4FNcy5V9bE+iHKCDDBdmTIRJ3Rt5I3dWBoxaBBncZ4dYsJletB/Zo15oIskB/55wTP+NZdW2M5wQDTZfW9H/nRocstyi+DmPBCYV4eRA3zN/Hzktz/VGnqfNFJUvlYuORX/KHyB6IEb/msff0=,iv:lkcoWl0fsx7xFa6NMHN797qY8Hcln69nILNNFxVJULg=,tag:lq34X0HbOoaH9dXT6lWMgA==,type:str]
sops:
  age:
    - recipient: age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb3hpWUVQMEVNRm5XQ0hP
        VVZ4M25NcWVwNVlHcVpkZ2xodk9YZmRrVjFZClRpViszZTZxMFFhMFM1cDZ3cnRD
        ZEhtU01iRjR4WTcrdWE0YkJPNEo2TWMKLS0tIDBaSHRKY1A2clRjSXBydE04RXF2
        ZTNjd2FvbEk5ZkhSMnIxM1BBWllEWTgKXtyEBhmw/s4qOx0uo24+wj/7M3n1g1rw
        YxwXqX7PZuI9ssdHZs6DdB30JoppJG/9d/ml8+KAV2zHmt08mieTyw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age13xfa77f49ne56z3yyqh9qc9upjmrjfva8kcvg3jfem2m99dhr9fs34gdrp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaGUxVVFOZjZoOFcxeVdB
        Q2t2L3RwZ29VVGtrdG5rdm81WTRYN1NiWUFRCmdnOHlGMzhHdlNYVjhPSzd2MkNB
        bWloWU1Wb3licXNFT2VkYkphTW84bTAKLS0tIDJaRFc4eU91bnlPb25xMTN2V3NL
        Y0JVSmdWVGErOHR5OURaWitkSmR5ZncK8HlxWOyKxPlKWjaJ+CMv527NU9bNlqM0
        C4kOuA8QQU51kc13CidF2CVoFqVaMnPIg5kXfKJptfXQ5QQEPYYgkg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qh2epukpmcg69386v5shr3w9l2tvryan4xr8npdk8tkth62jtpwqg4u0n3
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSVZMeGs4WldHLzRkdHdF
        VTRtdExseVlidmtUakJBQVNDUm83YlhVNUdJCnR4NU4rcGVBQzRIajU5bkJ2Tlhz
        SzFWeS95dHdPYVRiT3A2L2pVQUdwQ2MKLS0tIGs2MDNZT3ZWWFZJUUlJUG1DRUVx
        QTRPdkNCV0htOWd2bGJMUC9YaHJiMHMK/MtKYHJ13htFlZ3cLYRHl3l4k1xI14IQ
        bAzByiYM7ZFkTHgr0Rg5Jl1ryjhZ0Az7PJ0DwouZRHy63j/ux29IVg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1q2qaahrx4chvsa5g7xqwrwk28mld6kn4md8crcrqg046m8yt2efsugl8vr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbU1PanVZNlhCbkk0cHNN
        S1VYVG01ZEVBYWo1cWJlNXdlYjJvM1ZoU0h3Ck5CUUVvcVBldHJXWGg4b29kYnQ3
        WEFiQVRRWEFZMW4rUDEwNmlydzlOaVUKLS0tIDZVZXJST2JnNkRHejRzU0FhNXV6
        cWNRbDdCcTV5M2xQWHFVdCtGdi8zUTQK/ooZzXJReNPLiMo5O7ryNSSdFqczuWm4
        BTux6bHB8FRG9/Szl331K5YbxH6MwkY3M9BefxsNb1cT/hGS/dplIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T21:05:31Z"
  mac: ENC[AES256_GCM,data:5hfYMxpQ1PhcM6RnHNxQJOnT+U2c2rxSYTgT36e/VMjDS0WYvGVP/MvElyxHV1UeqerSCl0AtkWFfBV4bhNBNLKd2VN2DHUVwxHELMol+5QVe23B9pY5S0viBf5IGJ9EJSnoqlrmgK/MHGicaV54WUeQfHY53jtjVsmYhIyGonY=,iv:UubROhf6gvE8b2LHFh+dQkdeko7YLJXm/x39F1oyqeE=,tag:ktvW39SrMCJOeBRpaV/VfQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.1
